# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(null=True, upload_to=users.models.upload_logo_organization),
        ),
        migrations.AddField(
            model_name='provider',
            name='logo',
            field=models.ImageField(null=True, upload_to=users.models.upload_logo_provider),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=users.models.upload_avatar),
        ),
    ]
