# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160727_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='upload',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='user',
        ),
        migrations.AddField(
            model_name='provider',
            name='colonia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='company',
            field=models.CharField(default='H', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='cp',
            field=models.CharField(default='H', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='emails',
            field=models.EmailField(default='H', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='estado',
            field=models.CharField(default='H', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='exterior',
            field=models.CharField(default='H', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='interior',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='lastname',
            field=models.CharField(default='H', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='municipio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='street',
            field=models.CharField(default='H', max_length=100),
            preserve_default=False,
        ),
    ]
