# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160731_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='password',
            field=models.CharField(default='f5bb0c8de146c67b44babbf4e6584cc0', max_length=256),
            preserve_default=False,
        ),
    ]
