# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160731_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='phone',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
