# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_provider_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='observaciones',
            field=models.TextField(null=True),
        ),
    ]
