# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_provider_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='servicios_productos',
            field=models.TextField(default='Service desk, Hosting, Conmutador, Redes'),
            preserve_default=False,
        ),
    ]
