# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_provider_servicios_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='calificacion',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='puesto',
            field=models.CharField(default='Gerente', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='riesgo',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
