# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_orden_servicioorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='status',
            field=models.CharField(default='s', max_length=20),
            preserve_default=False,
        ),
    ]
