# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 04:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_orden_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 1, 4, 35, 11, 652044, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 1, 4, 35, 15, 356542, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicioorden',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicioorden',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 1, 4, 35, 20, 564328, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicioorden',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 1, 4, 35, 23, 619928, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
