# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_servicioorden_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='envio',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='total',
        ),
    ]
