# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_orden_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='observaciones',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='urgencia',
            field=models.CharField(default='Normal', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicioorden',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='servicioorden',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='servicioorden',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
