# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20160802_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='observaciones',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='status',
            field=models.CharField(default='Activada', max_length=20),
        ),
    ]
