# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20160802_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioorden',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
