# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_calificacionorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionorden',
            name='fecha_evaluacion',
            field=models.DateField(default='2016-03-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacionorden',
            name='recibio',
            field=models.CharField(default='', max_length=125),
            preserve_default=False,
        ),
    ]
