# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20160810_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('logo', models.ImageField(upload_to=users.models.upload_product)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Provider')),
            ],
        ),
    ]
