# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='servicios_productos',
            field=models.TextField(null=True),
        ),
    ]
