# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20160810_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='calificacion',
            field=models.IntegerField(null=True),
        ),
    ]
